### ISSUE TITLE
Access to the Properties

### ISSUE THREAD

**Issue by charan-r** [danmt/dynamic-component-loader#2]
return from(cl.loadChildren()).pipe(
      map((component: any) => this.cfr.resolveComponentFactory(component)),
      map(componentFactory => vcr.createComponent(componentFactory))
    );

It would be grateful, if have the access to the component instance, so that we can pass the input properties and emitter too.

**Comment by danmt** [comment]
You already have the instance. `vcr.createComponent(componentFactory)` returns the instance created, since I'm using a `map` operator, when you subscribe to this observable the emitted value will be the last instance created.

This is one way you could achieve what you describe:

```typescript
const componentInstance$ = from(cl.loadChildren()).pipe(
  map((component: any) => this.cfr.resolveComponentFactory(component)),
  map(componentFactory => vcr.createComponent(componentFactory))
);

componentInstance$.subscribe(componentInstance => {
  // Do what ever you want to the componentInstance
})
```
